---
- hosts: nodes
  gather_facts: no
 
  tasks: 
    - name: Insure docker servce is running 
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
      - docker.service
      - atomic-openshift-node.service
