---
- name: Update htpasswd Openshift 3.11
  hosts: masters[0]
  gather_facts: no
  
  tasks:
    - fetch:
        src: /etc/origin/master/htpasswd
        dest: "{{ playbook_dir }}/htpasswd-old"
        flat: yes

    - name: cleanup old backups 
      find:
        paths: /etc/origin/master
        patterns: htpasswd.*
      register: files_to_delete
    
    - name: List of files to remove 
      debug:
        msg: "files to be deleted {{ files_to_delete }}"
    
    - name: Removing old backups
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"
 
- name: Setting up htpasswd 
  hosts: localhost
  gather_facts: no
  no_log: true
  vars_prompt:
    - name: username
      prompt: User name to password for? 
      private: no
    
    - name: password1
      prompt: What is the password?

  vars:
    passfiles:
      - "{{ playbook_dir }}/htpasswd-new"
      - "{{ playbook_dir }}/htpasswd-old"
  
  tasks:
    - htpasswd:
        path: "{{ playbook_dir }}/htpasswd-new"
        name: "{{ username }}"
        password: "{{ password1 }}"
        crypt_scheme: apr_md5_crypt

    - name: Removing name to update 
      no_log: true
      lineinfile: 
        path: "{{ playbook_dir }}/htpasswd-old"
        state: absent
        regexp: '^{{ username }}'

    - name: read files
      no_log: true 
      command: "awk 1 {{ passfiles | join (' ') }}"
      register: pass_contents
    
    - name: Create new htpasswd
      no_log: true 
      copy:
        dest: "{{ playbook_dir }}/htpasswd"
        content: "{{ pass_contents.stdout_lines | unique | join('\n') }}"
    
- name: Copy back to mastes
  hosts: masters
  gather_facts: no
  no_log: True
  roles:
    - role: '{{playbook_dir}}'
  tasks:
    - name: Copy Back
      copy:
        backup: True 
        src: "{{ playbook_dir }}/htpasswd"
        dest: /etc/origin/master/htpasswd

- name: cleanup 
  hosts: localhost 
  gather_facts: no
  tasks:
    - name: File cleanup htpasswd
      file:
        state: absent
        path: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/htpasswd"
        - "{{ playbook_dir }}/htpasswd-new"
        - "{{ playbook_dir }}/htpasswd-old"




