kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-cluster-admin
  annotations:
    authorization.openshift.io/system-only: 'true'
    rbac.authorization.kubernetes.io/autoupdate: 'true'
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
  - verbs:
      - '*'
    nonResourceURLs:
      - '*'

