---
# Only infra and compute nodes, if masters need to be done they can be added in however it will impact cluster performace etc.. as the etcd will go down and may shift leaders a few times as this will not detect who is the leader and do it last.

- name: Setting Node to unscheduled 
  hosts: infra, compute 
  serial: 1
  tasks:
    - name: unscheduleing node
      k8s:
        definition:
          api_version: v1
          kind: Node
          metadata:
            name: "{{ inventory_hostname }}"
          spec:
            unschedulable: true
      delegate_to: "{{ groups.masters.0 }}"
    
    - name: stopping servies
      service: 
        name: "{{ item }}"
        state: stopped 
        enabled: no
      loop:
        - docker.service
        - atomic-openshift-node.service

    - name: rebooting host to free resources
      reboot:
        msg: "Wating for {{ inventory_hostname }} to come back"
    
    - name: Removing Directories
      file:
        state: absent
        path: "{{ item }}"
      loop:
      - /var/lib/origin/openshift.local.volumes
      - /var/lib/docker

    - name: Reset Docker Storage
      command: docker-storage-setup --reset
      register: dssreset

    - name: Reset output
      debug:
        msg: "Reset docker storage {{ dssreset }}"

    - name: Docker storage setup 
      command: docker-storage-setup
      register: dssetup

    - name: Setup output
      debug:
        msg: "Docker Storage Setup {{ dssetup }}"

    - name: Create Directory /var/lib/docker
      file:
        path: /var/lib/docker
        state: directory
       
    - name: Starting servies
      service: 
        name: "{{ item }}"
        state: started 
        enabled: yes
      with_items:
        - docker.service
        - atomic-openshift-node.service

    - name: Set node schedulable
      k8s:
        definition:
          api_version: v1
          kind: Node
          metadata:
            name: "{{ inventory_hostname }}"
          spec:
            unschedulable: false
      delegate_to: "{{ groups.masters.0 }}"
   
    - name: Check hosts status before continue
      shell: "oc get nodes {{ inventory_hostname }} | grep -iwo ready"
      delegate_to: 127.0.0.1
      register: nodestate
      until: nodestate.stdout == "Ready"
      retries: 20
      delay: 20

    - name: Check hosts status before continue
      shell: "oc get nodes {{ inventory_hostname }} | grep -iwo SchedulingDisabled | wc -l"
      delegate_to: 127.0.0.1
      register: nodeschedule
      until: nodeschedule.stdout == "0"
      retries: 5
      delay: 5
